apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: assets
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: assets
    spec:
      containers:
      - name: assets
        image: registry.cn-qingdao.aliyuncs.com/caonima/assets:2018-11-30-15-50
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: assets
spec:
  selector:
    run: assets
  type: NodePort
  ports:
  - nodePort: 30030
    port: 8080
    targetPort: 8080
