apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-suede
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    #nginx.ingress.kubernetes.io/rewrite-target: / 
spec:
  tls:
  - hosts:
    - www.xjlhcz.com
    secretName: yzb
  rules:
  - host: www.xjlhcz.com 
    http:
      paths:
      - path:  
        backend:
          serviceName: suede-ingress
          servicePort: 8080
      - path: /liam
        backend:
          serviceName: liam-ingress
          servicePort: 8090
