apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: suede-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: suede-ingress
    spec:
      containers:
      - name: suede-ingress
        image: 192.168.240.73/test/rapeworld:2019-07-05-22-07
        ports:
        - name: httpd 
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: suede-ingress
spec:
  selector:
    app: suede-ingress
  ports:
  - name: httpd
    port: 8080
    targetPort: 8080
