{\rtf1\ansi\ansicpg936\cocoartf1671\cocoasubrtf100
{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset134 PingFangSC-Regular;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 pipeline \{\
    agent any\
    tools \{ \
        //
\f1 \'b6\'a8\'d2\'e5
\f0 node
\f1 \'bb\'b7\'be\'b3
\f0 \
        maven 'mvn'\
        jdk 'jdk'\
    \}\
    \
    stages \{    \
        stage('get clone')\{\
            steps \{\
            //check CODE\
            echo 'Checkout==========
\f1 \'a1\'b7\'a1\'b7\'a1\'b7
\f0 '\
            git credentialsId: 'f921c9e0-0ec8-45c5-bb43-368d38f78ffe', url: 'http://202.107.190.8:10208/HaHa_Dog/BZYQ-End-Yq.git'\
            \}\
        \}\
        \
        stage('mvn test')\{\
            steps \{\
            //mvn test\
            echo "test ......" \
        		sh "mvn test"\
            \}\
        \}\
        \
        stage('mvn build')\{\
            steps \{\
            //mvn build\
            echo "deploy ......" \
        		sh "mvn clean install -Dmaven.test.skip=true"\
            \}\
        \}\
        \
        stage('deploy')\{\
            steps \{\
        	    //
\f1 \'d6\'b4\'d0\'d0\'b2\'bf\'ca\'f0\'bd\'c5\'b1\'be
\f0 \
        	    echo "deploy ......" \
        	        sh "sh cao.sh"\
        	    \}\
    	\}\
    \}\
    \
    post \{\
        success \{\
            emailext (\
                subject: "SUCCESSFUL: Job '$\{env.JOB_NAME\} [$\{env.BUILD_NUMBER\}]'",\
                body: """<p>SUCCESSFUL: Job '$\{env.JOB_NAME\} [$\{env.BUILD_NUMBER\}]':</p>\
                <p>Please test at "<a href="218.84.186.2:30012">218.84.186.2:30012</a>"</p>""",\
                to: "837213832@qq.com",\
                from: "ws1018ws@qq.com"\
            )\}\
        failure \{\
            emailext (\
                subject: "FAILED: Job '$\{env.JOB_NAME\} [$\{env.BUILD_NUMBER\}]'",\
                body: """<p>FAILED: Job '$\{env.JOB_NAME\} [$\{env.BUILD_NUMBER\}]':</p>\
                <p>Check console output at "<a href="218.84.186.2:30012">$\{env.JOB_NAME\} [$\{env.BUILD_NUMBER\}]</a>"</p>""",\
                to: "837213832@qq.com",\
                from: "ws1018ws@qq.com"\
            )\}\
    \}\
\}}