apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master1-pv
spec:
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 192.168.240.59
    path: /data/mysql/master/master0/
