apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: examen
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: examen
    spec:
      containers:
      - name: examen
        image: registry.cn-qingdao.aliyuncs.com/caonima/examen:2018-11-20-16-30
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: examen
spec:
  selector:
    run: examen
  type: NodePort
  ports:
  - nodePort: 30050
    port: 8080
    targetPort: 8080
