apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-10-21T03:26:24Z"
  name: default
  namespace: default
  resourceVersion: "349"
  selfLink: /api/v1/namespaces/default/serviceaccounts/default
  uid: d56748e4-3e28-4dc1-8b81-4fd83cc147bf
secrets:
- name: default-token-8k7rj
imagePullSecrets:
- name: myregistrykey
