apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: appdownload-t
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: appdownload-t
    spec:
      containers:
      - name: appdownload-t
        image: 192.168.188.77:5000/xiazai:test4
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: appdownload-t
spec:
  selector:
    run: appdownload-t
  type: NodePort
  ports:
  - nodePort: 31006
    port: 8088
    targetPort: 8088

