apiVersion: v1
kind: Service
metadata:
  name: zoo1-nodeport
  labels:
    app: zookeeper-1
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    nodePort: 32181
    targetPort: 2181
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zoo2-nodeport
  labels:
    app: zookeeper-2
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    nodePort: 32182
    targetPort: 2181
  selector:
    app: zookeeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: zoo3-nodeport
  labels:
    app: zookeeper-3
spec:
  type: NodePort
  ports:
  - name: client
    port: 2181
    nodePort: 32183
    targetPort: 2181
  selector:
    app: zookeeper-3