apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master1-pv
spec:
  capacity:
    storage: 1024G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 192.168.100.3
    path: /data/mysql/master1/
