apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv1
spec:
  capacity:
    storage: 1Gi
  volumeMode: redisFile
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  cephfs:
    monitors:
      - 192.168.1.103:6789
    path: "/redis/pv1"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv2
spec:
  capacity:
    storage: 1Gi
  volumeMode: redisFile
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  cephfs:
    monitors:
      - 192.168.1.103:6789
    path: "/redis/pv2"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv3
spec:
  capacity:
    storage: 1Gi
  volumeMode: redisFile
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  cephfs:
    monitors:
      - 192.168.1.103:6789
    path: "/redis/pv3"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv4
spec:
  capacity:
    storage: 1Gi
  volumeMode: redisFile
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  cephfs:
    monitors:
      - 192.168.1.103:6789
    path: "/redis/pv4"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv5
spec:
  capacity:
    storage: 1Gi
  volumeMode: redisFile
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  cephfs:
    monitors:
      - 192.168.1.103:6789
    path: "/redis/pv5"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv6
spec:
  capacity:
    storage: 1Gi
  volumeMode: redisFile
  accessModes:
    - ReadWriteMany
  storageClassName: redis
  cephfs:
    monitors:
      - 192.168.1.103:6789
    path: "/redis/pv6"
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
