apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc-1
  namespace: ns-elasticsearch
spec:
  accessModes:
    - ReadWriteMany
  volumeName: es-pv-1
  resources:
    requests:
      storage: 900G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc-2
  namespace: ns-elasticsearch
spec:
  accessModes:
    - ReadWriteMany
  volumeName: es-pv-2
  resources:
    requests:
      storage: 900G
