docker stop tracker1
docker stop tracker2
docker stop tracker3
docker stop tracker4
docker stop tracker5
docker stop storage1
docker stop storage2
docker stop storage3
docker stop storage4
docker stop storage5
docker stop storage6
docker stop storage7
docker stop storage8
docker stop storage9
docker stop storage10
