apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: suede
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: suede
    spec:
      containers:
        - name: suede
          image: 192.168.240.73/test/suede:2019-06-12-14-28
          ports:
            - name: httpd
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: suede
spec:
  selector:
    run: suede
  type: NodePort
  ports:
    - name: httpd
      nodePort: 30011
      port: 8080
      targetPort: 8080
