apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master1-pv
spec:
  capacity:
    storage: 30G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: 10.1.11.26
    path: /home/lhcz/mysql/master/master1/
