apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fuck-world
  namespace: cao
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: fuck-world
    spec:
      containers:
      - name: fuck-world
        image: 192.168.159.130:5000/fuck-world:2018-09-03
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fuck-world
spec:
  selector:
    run: fuck-world
  type: NodePort
  ports:
  - nodePort: 30005
    port: 8080
    targetPort: 8080
