apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: registry.cn-qingdao.aliyuncs.com/caonima/assets:2018-12-07-16-14
  imagePullSecrets:
    - name: myregistrykey
