apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: demo-pv
  resources:
    requests:
      storage: 20G
  storageClassName: nfs 
