apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    args:
    image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
#        httpHeaders:
#          - name: X-Custom-Header
#            value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
