docker load -i 1.tar
docker load -i 2.tar
docker load -i 3.tar
docker load -i 4.tar
docker load -i 5.tar
docker load -i 6.tar
docker load -i 7.tar
docker load -i 8.tar
docker load -i 9.tar
docker load -i 0.tar